resource_types:

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:

  - name: repo-upstream-base
    type: git
    icon: github
    check_every: 1h
    source:
      uri: https://((secrets.github_token))@github.com/((organization_upstream))/((repository_name)).git
      branch: ((base_branch_upstream))

  - name: repo-fork-base
    type: git
    icon: github
    check_every: 1h
    source:
      uri: https://((secrets.github_token))@github.com/((organization_fork))/((repository_name)).git
      branch: ((base_branch_upstream))

  - name: repo-fork
    type: git
    icon: github
    check_every: 1h
    source:
      uri: https://((secrets.github_token))@github.com/((organization_fork))/((repository_name)).git
      branch: ((base_branch_fork))

  - name: ci-branch
    type: git
    icon: github
    check_every: 1h
    source:
      uri: https://((secrets.github_token))@github.com/((organization_fork))/((repository_name)).git
      branch: ((ci_branch))

  - name: slack-notification
    type: slack-notification
    icon: slack
    source:
      url: ((secrets.slack_url))

  - name: catalog-chart-version
    type: semver
    source:
      driver: git
      initial_version: 0.0.0
      uri: https://((secrets.github_token))@github.com/((organization_fork))/((repository_name)).git
      branch: version-catalog-chart
      file: version


jobs:

  - name: sync-base-branch
    serial: true
    plan:
      - get: repo-upstream-base
        trigger: true
      - put: repo-fork-base
        params:
          repository: repo-upstream-base

  - name: create-pull-request
    serial: true
    plan:
      - get: repo-fork-base
        trigger: true
      - get: repo-fork
      - get: ci-branch

      - task: create-pull-request
        file: ci-branch/ci/tasks/create-pull-request.yml
        input_mapping:
          pull-request-input: repo-fork-base
          source: repo-fork
        params:
          GITHUB_TOKEN: ((secrets.github_token))
          BASE_OWNER: ((organization_fork))
          BASE_BRANCH: ((base_branch_fork))
          HEAD_OWNER: ((organization_fork))
          HEAD_BRANCH: ((base_branch_upstream))
          MESSAGE: 'Automatic update from upstream'

      - task: prepare-slack-notification
        file: ci-branch/ci/tasks/prepare-slack-message.yml
        input_mapping:
          slack-message-input: pull-request-output
        params:
          MESSAGE: Service catalog upstream updated. Consider merging the PR.
          BUTTONS:
            - text: Pull Request
              url: slack-message-input/url.txt
              type: button
              style: primary

      - put: slack-notification
        params:
          username: ((slack_username))
          channel: ((slack_channel))
          icon_url: ((slack_icon))
          attachments_file: slack-message-output/attachments.json

  - name: 'release-service-catalog'
    plan:
      - in_parallel:
          - get: repo-fork
          - get: ci-branch

          - get: catalog-chart-version
            params:
              bump: patch

      - task: service-catalog-create-chart
        file: ci-branch/ci/tasks/create-chart.yml
        input_mapping:
          version: catalog-chart-version
          source-code: repo-fork
        params:
          ARTIFACTORY_USERNAME: ((defaults.artifactory_username))
          ARTIFACTORY_PASSWORD: ((defaults.artifactory_password))
          CHART_REPO: ((defaults.helm_repo_url))
          CHART_NAME: catalog
          CHART_PATH: source-code/charts/catalog

      - put: catalog-chart-version
        params:
          file: catalog-chart-version/version
