resources:

  - name: repo-upstream-base
    type: git
    icon: github
    source:
      uri: https://((secrets.github_token))@github.com/((organization_upstream))/((repository_name)).git
      branch: ((base_branch_upstream))

  - name: repo-fork-base
    type: git
    icon: github
    source:
      uri: https://((secrets.github_token))@github.com/((organization_fork))/((repository_name)).git
      branch: ((base_branch_upstream))

jobs:

  - name: sync-base-branch
    serial: true
    plan:
      - get: repo-upstream-base
        trigger: true
      - put: repo-fork-base
        params:
          repository: repo-upstream-base
